{% set name = "dargs" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/deepmodeling/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e81840ef7507d6ae8322001532231bd41a42f974f2559a0aa275ef5e9713242e

build:
  number: 0
  noarch: python
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm

  run:
    - python >=3.6

test:
  requires:
    - pip
  imports:
    - dargs
  commands:
    - python -m pip check dargs

about:
  home: https://github.com/deepmodeling/dargs
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Process arguments for the deep modeling project.
  doc_url: https://github.com/deepmodeling/dargs
  dev_url: https://github.com/deepmodeling/dargs

extra:
  recipe-maintainers:
    - njzjz
